CREATE PROC Bai2_2 @mada INT
AS
BEGIN
	SELECT COUNT(MANV) AS 'So luong NV', MADA, TENPHG
	FROM PHONGBAN
	INNER JOIN DEAN ON DEAN.PHONG = PHONGBAN.MAPHG
	INNER JOIN NHANVIEN ON NHANVIEN.PHG = PHONGBAN.MAPHG
	WHERE MADA = @mada
	GROUP BY TENPHG, MADA
END

EXEC Bai2_2 1