CREATE PROC Bai2_4 @trphg VARCHAR (20)
AS
BEGIN
	SELECT HONV, TENLOT, TENNV, TENPHG, NHANVIEN.MANV
	FROM NHANVIEN
	INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
	LEFT OUTER JOIN THANNHAN ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
	WHERE THANNHAN.MA_NVIEN IS NULL AND TRPHG = @trphg
END

EXEC Bai2_4 '008'