----CHUVI-DIENTICH----
DECLARE @CHUVI INT, @DIENTICH INT, @CHIEUDAI INT, @CHIEURONG INT
SET @CHIEUDAI = 6 ---CHIỀU DÀI = 6---
SET @CHIEURONG = 3 ---CHIỀU RỘNG = 3---
SET @CHUVI= (@CHIEUDAI + @CHIEURONG) * 2
SET @DIENTICH=@CHIEUDAI*@CHIEURONG
SELECT @CHUVI AS 'CHU VI HÌNH CHỮ NHẬT'
SELECT @DIENTICH AS 'DIỆN TÍCH HÌNH CHỮ NHẬT'
